name: Backend CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install pipenv
        run: |
          python -m pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install
          pipenv run pip install flake8
      
      - name: Run linting
        run: |
          pipenv run flake8

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install

      - name: Run tests
        run: pipenv run test

  build:
    name: Build Docker Image
    needs: [lint, test]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        working-directory: ./starter/backend
        run: docker build -t backend:${{ github.sha }} .